# Base Settings
title: Tohuw.Net
email: ron@tohuw.net
description: >
  Ron Scott-Adams is a Systems Engineer, with a passion for
  creating, maintaining and explaining well-designed data centers,
  virtualization solutions, and information technology systems.
baseurl: ''
url: "https://tohuw.net"
timezone: America/New_York

# Metadata
language: en
author: Ron Scott-Adams
subtitle: Blinkenlights, Virtualization, & Yak Shaving

# Menu
menuicons: true
menuitem_articles: true
menuitem_tags: true
menuitem_social: true

# Search
search_enabled: true
search_placeholder: "&#xf002;"

# Categories
categories_display: false

# Tags
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty
ignored_tags:

# Social
social_title:
rss_title: icon
twitter_title: icon
twitter_username: tohuw
twitter_hashtag: :slug
linkedin_title: icon
linkedin_username: tohuw
github_title: icon
github_username:  tohuw
facebook_title: icon
facebook_username: tohuw
disqus_shortname:

# Recent Posts List
recentposts_display: true
recentposts_title: More, Here
recentposts_count: 3

# Blogroll
blogroll_title: More, Elsewhere
blogroll_footer_count: 4
blogroll:
    - name: Yellow Bricks
      subtitle: Great, usable thoughts about VMware products
      url: http://yellow-bricks.com
    - name: Dadhacker
      subtitle: Atari, Apple, Microsoft... He's seen some things
      url: http://dadhacker.com
    - name: Cormac Hogan
      subtitle: Software-Defined Storage Guru Extraordinaire
      url: http://cormachogan.com
    - name: Punching Clouds
      subtitle: Virtualization and cloud stuff from a VMware Architect

# Front Matter Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Layout: readtime
readtime_display: true
readtime_title: icon

# License
license_display: true
license_title: "CC BY-NC-SA 4.0"
license_url: https://tohuw.net/rights/

# Analytics
# piwik_url: https://tohuw.net/stats
# piwik_siteid: 1

# Build settings
destination: ../tohuw.github.io
include:
  - /_pages
exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
permalink: /articles/:title

# Layout: compress
compress_html:
  ignore:
    envs: [development]

# Plugin: jekyll-assets
assets:
  cache: false
  digest: false
  autoprefixer:
    browsers: ["last 2 versions","> 5%","IE 9"]
