# Base Settings
title: Tohuw.Net
email: ron@tohuw.net
description: >
  Ron Scott-Adams is a Systems Engineer with a passion for
  creating and explaining well-designed data centers
  and next-generation application platforms.
baseurl: ''
url: "https://tohuw.net"
timezone: America/Chicago

# Metadata
language: en
author: Ron Scott-Adams
subtitle: Clouds, Chaos, & Yak Shaving

# Menu
menuicons: true
menuitem_articles: true
menuitem_tags: true
menuitem_social: true

# Search
search_enabled: true
search_placeholder: "&#xf002; Search..."

# Categories
categories_display: false

# Tags
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty
ignored_tags:

# Social
social_title:
rss_title: icon
twitter_title: icon
twitter_username: tohuw
twitter_hashtag: :slug
linkedin_title: icon
linkedin_username: tohuw
github_title: icon
github_username:  tohuw
facebook_title: icon
facebook_username: tohuw
disqus_shortname: tohuw

# Recent Posts List
recentposts_display: true
recentposts_title: More, Here
recentposts_longcount: 25
recentposts_shortcount: 3
recentposts_meta: true
recentposts_moremeta: false

# Blogroll
blogroll_title: More, Elsewhere
blogroll_footer_count: 4
blogroll:
    - name: Yellow Bricks
      subtitle: Great, Usable Thoughts about the Virtualization World
      url: http://yellow-bricks.com
    - name: Cormac Hogan
      subtitle: Software-Defined Storage Guru Extraordinaire
      url: http://cormachogan.com
    - name: Virtually Ghetto
      subtitle: A Virtual Automation & Lab Genius
      url: http://virtuallyghetto.com
    - name: Dadhacker
      subtitle: Atari, Apple, Microsoft... He's seen some things
      url: http://dadhacker.com

# Front Matter Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Layout: readtime
readtime_display: true
readtime_title: icon

# Layout: nowlistening
nowlistening_display: true
nowlistening_title: icon

# License
license_display: true
license_title: "CC BY-NC-SA 4.0"
license_url: /rights/

# Analytics
# piwik_url: https://stats.tohuw.net/
# piwik_siteid: 1

# Build settings
destination: ../tohuw.github.io
include:
  - /_pages
exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
permalink: /articles/:title

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: true

# Plugin: jekyll-assets
assets:
  assets:
    - "*.woff"
    - "*.woff2"
  cache: false
  digest: false
  autoprefixer:
    browsers: ["last 2 versions","> 5%","IE 9"]
