# Site settings
title: Tohuw.Net
email: ron@tohuw.net
description: >
  Ron Scott-Adams is a Systems Engineer, with a passion for
  creating, maintaining and explaining well-designed data centers,
  virtualization solutions, and information technology systems.
baseurl: ''
url: "https://tohuw.net"
timezone: America/New_York

# Social settings
twitter_username: tohuw
github_username:  tohuw

# Front Matter Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "pages"

# Build settings
markdown: kramdown
destination: ../tohuw.github.io
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
permalink: /articles/:title
